[plugin]
repository = "https://github.com/LadyDefile/Wordsmith-DalamudPlugin.git"
commit = "2755aa7f044c1eddaa77fe6c66328dafdbbf44c5"
owners = [
    "LadyDefile"
]
project_path="Wordsmith"
changelog = "Minor update in an attempt to fix a bug."
