[plugin]
repository = "https://github.com/LadyDefile/Wordsmith-DalamudPlugin.git"
commit = "f948da0f974d0b10e2b1147991e07926a7708b6c"
owners = [
    "LadyDefile"
]
project_path="Wordsmith"
changelog = "Optimized several sections of code. Updated thesaurus to use Merriam-Webster API. Fixed several bugs."
