[plugin]
repository = "https://github.com/LadyDefile/Wordsmith-DalamudPlugin.git"
commit = "ef4c68c9f6c9228b3e1f09390439d12ab3448557"
owners = [
    "LadyDefile"
]
project_path="Wordsmith"
changelog = """# Wordsmith v1.11.1 Patch Notes:
[FIXED] Fixed a crash related to zero-length words in the Tally system."""
