[plugin]
repository = "https://github.com/LadyDefile/Wordsmith-DalamudPlugin.git"
commit = "92e3d601ada55e7f05a42eec30c30fa7a6dc806e"
owners = [
    "LadyDefile"
]
project_path="Wordsmith"
changelog = "Optimized several sections of code. Updated thesaurus to use Merriam-Webster API. Fixed several bugs."
