[plugin]
repository = "https://github.com/LadyDefile/Wordsmith-DalamudPlugin.git"
commit = "cac0ddafc27ad8189c5f79485117ad44cab9c3c2"
owners = [
    "LadyDefile"
]
project_path="Wordsmith"
changelog = "Optimized several sections of code. Updated thesaurus to use Merriam-Webster API. Fixed several bugs."
