[plugin]
repository = "https://github.com/LadyDefile/Wordsmith-DalamudPlugin.git"
commit = "138dc57b3ccf9819025282db6677f498cc7122cf"
owners = [
    "LadyDefile"
]
project_path="Wordsmith"
changelog = "Fixed several bugs."